language: go

branches:
  only:
    - master

go:
  - 1.8.3

install:
  - go get -u github.com/golang/lint/golint
  - go get github.com/lfittl/pg_query_go
  - export PATH=$PATH:$HOME/.local/bin

script:
  - golint
  - go vet ./...
  - go test -v ./... -cover

notifications:
  email:
    on_success: change
    on_failure: always
