language: go

branches:
  only:
    - master

go:
  - 1.11.x

install:
  - go get -t -v ./...
  - go get -u golang.org/x/lint/golint
  - export PATH=$PATH:$HOME/.local/bin

script:
  - go vet ./...
  - golint -set_exit_status ./...
  - gofmt -l . | exit $(wc -l)
  - go test -v ./... -cover -race

notifications:
  slack:
    rooms:
      secure: tretY3UfnXcDk9s00M0SO9/q5btNaG+bILOjlTuLYGXZdKB4nlrSVQk1vVp0UewFr+8iaHc2PD5o0ICAK4XBxErEZ+OiY0mC0ATggj7R8XQB0C8q5O0osBPGZ/QzU2ZQkUFDVbd4MwAFRCioZTSFDop9GRzA3wT5+S49wgr7msVDDRJFqvSQhaalgFkYpWae5AdMAL4UrWcBU2HSI1Llk1iA9xkorS0T2MFOJJnsn3vePPSyAa5vMXQ6kjpOcfi+q6cuTq2lwkyTGLKyxd0r30lc/1khBMGx3pLeAMU3cqX8lj6FE1wlfQdMIpqDXLDanbI1NQqNtKXPhTuCtdvrDmkpTQmYQLuEoe+73TMD4HIPdQhcJsqE9ixmRhz1Pd3IdvrwNT9/vMWEtl9WEzjODnPuFjyQtUWAiOHUrLbozkse1Vx71mNKyCeIslYC/8LBYQHSRwEgdYvUk3hAGCbyCdKHDEbf4j1cORdGQgn0u52F1Iyxg9QIK6ru5I7u3PEFriDYg8XwJ5wRBJUPsdZ+U+SuoaUUdeuigMe5zRjDIqSF4Dj9s3nXfMkNFL0yfjpharpl65DjbxUUWxfJvIQiSadUjGkL/LwIbJesVZXgZMaZdILfyyDpCR24R0rJw7Y0DXzSIXNXEOAssphYvMMbFlyqbDXR8EkgR05Pok58kUg=
    on_pull_requests: false
    on_success: change
    on_failure: always
  email:
    recipients:
      - hackers@panoply.io
    on_success: change
    on_failure: always
