language: go

branches:
  only:
    - master

go:
  - 1.10.x

env:
  global:
    # require by lfittl/pg_query_go. this flag is unrecognized by >=go1.9.4.
    # TODO remove once go's whitelist will include it. see https://github.com/golang/go/issues/23749
    - CGO_LDFLAGS_ALLOW='-fstack-protector'

install:
  - go get -u github.com/golang/lint/golint
  - go get github.com/lfittl/pg_query_go
  - export PATH=$PATH:$HOME/.local/bin

script:
  - go tool vet .
  - golint -set_exit_status ./...
  - gofmt -l . | exit $(wc -l)
  - go test -v ./... -cover -race

notifications:
  slack:
    rooms:
      - panoplyio:LeK4hoOIDsRiBBAhgXKnSAD0#builds
    on_pull_requests: false
    on_success: change
    on_failure: always
  email:
    recipients:
      - hackers@panoply.io
    on_success: change
    on_failure: always
